name: Build Minizinc

env:
  BUILD_CONTEXT: ./minizinc

on:
  workflow_dispatch:
    inputs:
      push-images:
        description: "Push built images to registries"
        required: true
        type: boolean
        default: false
  push:
    branches:
      - main
    paths:
      - "minizinc/**"
      - "variables.env"
  pull_request:
    branches:
      - main
    paths:
      - "minizinc/**"
      - "variables.env"

  workflow_call:
    secrets:
      REGISTRY_PASSWORD_DOCKER:
        required: true
      PUBLISH_TO_GITHUB_REPO_TOKEN:
        required: true
    inputs:
      push-images:
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHOULD_PUSH: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || inputs.push-images || false }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0

      - run: ls -l
      - run: cat ./variables.env >> $GITHUB_ENV
      - run: cat ${{ env.BUILD_CONTEXT }}/variables.env >> $GITHUB_ENV

      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        if: ${{ env.SHOULD_PUSH }}
        with:
          username: ${{ env.REGISTRY_USERNAME_DOCKER }}
          password: ${{ secrets.REGISTRY_PASSWORD_DOCKER }}

      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        if: ${{ env.SHOULD_PUSH }}
        with:
          registry: ghcr.io
          username: ${{ env.REGISTRY_USERNAME_GHCR }}
          password: ${{ secrets.PUBLISH_TO_GITHUB_REPO_TOKEN }}

      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: ${{ env.BUILD_CONTEXT }}
          push: ${{ env.SHOULD_PUSH }}
          tags: |
            ${{ env.REGISTRY_USERNAME_DOCKER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ env.REGISTRY_USERNAME_GHCR }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
